name: Deploy Plugin to WordPress
on:
  push:
    branches:
      - main
      - release/lifecycle # هيشتغل أول ما تعمل Push للبرانش ده

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync files to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_MUSERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # المسار اللي هيترفع فيه البلجن (عدله حسب سيرفرك)
          server-dir: public_html/wp-content/plugins/woo-step-finder/
          # استثناء ملفات الـ Git عشان متترفعش على السيرفر
          exclude: |
            **/.git*
            **/.github*
            README.md
